// All UI strings in English. Translated dynamically by Claude for other languages.
// Strings with variables use {varName} placeholder syntax — use fill() at render time.

export interface UiStrings {
  // Hero
  hero_badge: string
  hero_title1: string
  hero_title2: string
  hero_subtitle: string
  hero_description: string
  hero_cta: string
  hero_starting_at: string
  hero_social_proof: string

  // Example certificate preview
  example_label: string
  example_cert_this_is_to: string
  example_cert_body: string
  example_cert_caption: string

  // Tiers section
  tiers_heading1: string
  tiers_heading2: string
  tiers_subheading: string
  tiers_most_popular: string
  tiers_one_time: string
  tiers_get_cta: string // "Get {name}"

  // Tier data — Basic
  tier_basic_name: string
  tier_basic_tagline: string
  tier_basic_f1: string
  tier_basic_f2: string
  tier_basic_f3: string
  tier_basic_f4: string
  tier_basic_f5: string

  // Tier data — Premium
  tier_premium_name: string
  tier_premium_tagline: string
  tier_premium_f1: string
  tier_premium_f2: string
  tier_premium_f3: string
  tier_premium_f4: string
  tier_premium_f5: string
  tier_premium_f6: string
  tier_premium_f7: string

  // Tier data — Supreme
  tier_supreme_name: string
  tier_supreme_tagline: string
  tier_supreme_f1: string
  tier_supreme_f2: string
  tier_supreme_f3: string
  tier_supreme_f4: string
  tier_supreme_f5: string
  tier_supreme_f6: string
  tier_supreme_f7: string

  // FAQ
  faq_heading: string
  faq_q1: string; faq_a1: string
  faq_q2: string; faq_a2: string
  faq_q3: string; faq_a3: string
  faq_q4: string; faq_a4: string

  // Final CTA
  fence_heading: string
  fence_sub: string
  fence_cta: string

  // Footer
  footer_rights: string
  footer_disclaimer: string

  // Checkout
  checkout_title: string
  checkout_name_label: string
  checkout_name_placeholder: string
  checkout_title_label: string
  checkout_title_hint: string
  checkout_title_placeholder: string
  checkout_title_note: string
  checkout_submit_btn: string   // "Pay {price} & Get Certified →"
  checkout_loading_btn: string
  checkout_secure_note: string
  checkout_included_label: string
  checkout_cancelled_msg: string
  checkout_invalid_tier: string
  checkout_back: string

  // Certificate page
  cert_loading_title: string
  cert_loading_subtitle: string
  cert_error_title: string
  cert_try_again: string
  cert_back_home: string
  cert_success_title: string
  cert_success_subtitle: string
  cert_download_btn: string
  cert_downloading_btn: string
  cert_share_btn: string
  cert_sharing_btn: string
  cert_share_alert: string
  cert_twitter_text: string
  cert_share_twitter: string
  cert_share_linkedin: string
  cert_know_someone: string
  cert_get_another: string

  // Certificate display (inside the certificate document)
  cd_this_is_to: string
  cd_honors: string
  cd_achievements: string
  cd_issued: string
  cd_cert_num: string
  cd_tagline: string
}

export const EN: UiStrings = {
  hero_badge: 'Internationally Recognized · AI-Powered · Absolutely Official',
  hero_title1: 'Certified',
  hero_title2: 'Not Stupid™',
  hero_subtitle: 'Finally prove what your mother always knew.',
  hero_description:
    'Get an AI-generated, officially official certificate proving your cognitive non-deficiency. Perfect for LinkedIn, TikTok, or framing above your desk.',
  hero_cta: 'Get Certified Now ↓',
  hero_starting_at: 'Starting at $2.99',
  hero_social_proof: '⭐⭐⭐⭐⭐ "My employer finally believes I\'m not stupid." — Recent Customer',

  example_label: 'Example Certificate',
  example_cert_this_is_to: 'This is to certify that',
  example_cert_body:
    'has successfully passed the Minimal Cognitive Competency Assessment and is hereby officially declared NOT STUPID by an organization that definitely exists.',
  example_cert_caption: '^ Yours will have unique AI-generated wording. Much funnier.',

  tiers_heading1: 'Choose Your Level of',
  tiers_heading2: 'Official Smartness',
  tiers_subheading: 'Each certificate is uniquely generated by Claude AI. No two are the same.',
  tiers_most_popular: '⭐ MOST POPULAR',
  tiers_one_time: 'one-time',
  tiers_get_cta: 'Get {name}',

  tier_basic_name: 'Not Stupid Certificate',
  tier_basic_tagline: 'Prove the baseline',
  tier_basic_f1: 'Official-looking design',
  tier_basic_f2: 'AI-generated unique funny text',
  tier_basic_f3: 'Your name in big fancy letters',
  tier_basic_f4: 'Downloadable as image',
  tier_basic_f5: 'Shareable to socials',

  tier_premium_name: 'Certified Genius',
  tier_premium_tagline: 'Above average, allegedly',
  tier_premium_f1: 'Gold border design',
  tier_premium_f2: 'Elaborate AI-generated wording',
  tier_premium_f3: 'Fake impressive credentials',
  tier_premium_f4: 'Fake achievements & honors',
  tier_premium_f5: 'Your job title (elevated)',
  tier_premium_f6: 'Downloadable as image',
  tier_premium_f7: 'Shareable to socials',

  tier_supreme_name: 'Galaxy Brain Supreme',
  tier_supreme_tagline: 'A mind beyond comprehension',
  tier_supreme_f1: 'Most elaborate design',
  tier_supreme_f2: 'AI roasts everyone else as dumber',
  tier_supreme_f3: 'Fake PhD title',
  tier_supreme_f4: 'Honorary memberships to made-up institutions',
  tier_supreme_f5: 'Multiple prestigious fake awards',
  tier_supreme_f6: 'Downloadable as image',
  tier_supreme_f7: 'Shareable to socials',

  faq_heading: 'Frequently Asked Questions',
  faq_q1: 'Is this certificate legally recognized?',
  faq_a1: "Absolutely. By the International Bureau of Human Intelligence Standards, the Global Council of Non-Stupidity, and your mother (pending verification).",
  faq_q2: 'Can I put this on my LinkedIn?',
  faq_a2: "We strongly encourage it. Nothing says 'hire me' like official certification that you are, in fact, not stupid.",
  faq_q3: 'What if I am actually stupid?',
  faq_a3: "The certificate covers that. It says 'NOT STUPID' right there. That's legally binding in at least 3 made-up countries.",
  faq_q4: 'Can I buy one for someone else?',
  faq_a4: "Excellent gift idea. Perfect for that friend who just made a questionable life decision. You know the one.",

  fence_heading: 'Still on the fence? 🤔',
  fence_sub: "The longer you wait, the longer you remain uncertified. Don't be that person.",
  fence_cta: 'Get Certified — From $2.99',

  footer_rights: '© 2026 Certified Not Stupid™',
  footer_disclaimer:
    "Satirical entertainment product. This certificate confers no legal rights, academic recognition, or actual proof of intelligence. The International Bureau of Human Intelligence Standards does not exist. Or does it?",

  checkout_title: 'Get Your Certificate',
  checkout_name_label: 'Your Name',
  checkout_name_placeholder: 'The name to immortalize on this certificate',
  checkout_title_label: 'Job Title / Role',
  checkout_title_hint: '(optional but funnier)',
  checkout_title_placeholder: 'e.g., Senior Napper, Aspiring Adult, CEO of Nothing',
  checkout_title_note: 'Claude AI will incorporate this into your certificate wording.',
  checkout_submit_btn: 'Pay {price} & Get Certified →',
  checkout_loading_btn: '⏳ Redirecting to payment...',
  checkout_secure_note: '🔒 Secured by Paddle. We never store your card details.',
  checkout_included_label: "What's included",
  checkout_cancelled_msg: "😅 Payment was cancelled. Your stupidity remains uncertified... for now.",
  checkout_invalid_tier: 'Invalid tier selected.',
  checkout_back: '← Back to all tiers',

  cert_loading_title: 'Generating your official certificate...',
  cert_loading_subtitle: 'Claude AI is carefully crafting your unique credentials. This takes a few seconds.',
  cert_error_title: 'Something went wrong',
  cert_try_again: 'Try Again',
  cert_back_home: 'Back to Home',
  cert_success_title: '🎉 Your Certificate is Ready!',
  cert_success_subtitle: 'Officially verified and absolutely real. Frame it. Put it on LinkedIn. Tell your parents.',
  cert_download_btn: '⬇️ Download Certificate',
  cert_downloading_btn: '⏳ Saving...',
  cert_share_btn: '📱 Share to TikTok / Instagram',
  cert_sharing_btn: '⏳ Preparing...',
  cert_share_alert: 'Certificate saved! Now share it on TikTok or Instagram 📱',
  cert_twitter_text: "I am officially Certified Not Stupid™ 🎓 Get yours at notstupidcert.com",
  cert_share_twitter: 'Share on X/Twitter',
  cert_share_linkedin: 'Share on LinkedIn',
  cert_know_someone: 'Know someone who needs this? 👀',
  cert_get_another: 'Get Another Certificate →',

  cd_this_is_to: 'This is to certify that',
  cd_honors: 'Honors & Distinctions',
  cd_achievements: 'Notable Achievements',
  cd_issued: 'Issued:',
  cd_cert_num: 'Cert #:',
  cd_tagline: 'notstupidcert.com — Internationally Recognized Since 2026',
}

/** Replace {varName} placeholders in a template string. */
export function fill(template: string, vars: Record<string, string>): string {
  return Object.entries(vars).reduce(
    (s, [k, v]) => s.replaceAll(`{${k}}`, v),
    template
  )
}

export function tierFeatures(tr: UiStrings, id: 'basic' | 'premium' | 'supreme'): string[] {
  if (id === 'basic') return [tr.tier_basic_f1, tr.tier_basic_f2, tr.tier_basic_f3, tr.tier_basic_f4, tr.tier_basic_f5]
  if (id === 'premium') return [tr.tier_premium_f1, tr.tier_premium_f2, tr.tier_premium_f3, tr.tier_premium_f4, tr.tier_premium_f5, tr.tier_premium_f6, tr.tier_premium_f7]
  return [tr.tier_supreme_f1, tr.tier_supreme_f2, tr.tier_supreme_f3, tr.tier_supreme_f4, tr.tier_supreme_f5, tr.tier_supreme_f6, tr.tier_supreme_f7]
}
