import Image from 'next/image'
import LanguagePicker from '@/components/LanguagePicker'
import { getLanguage } from '@/lib/get-language'
import { TIERS, TierId, LEMON_SQUEEZY_URLS } from '@/lib/tiers'
import { getTranslations, tierFeatures } from '@/lib/translate'

const TIER_CTAS: Record<TierId, string> = {
  basic: 'Certify Me Now →',
  premium: "I'm a Genius →",
  supreme: 'Unlock Galaxy Brain →',
}

const TESTIMONIALS = [
  {
    quote: "I framed it next to my actual degree. My parents finally stopped crying.",
    name: "Kevin L.",
    tier: "Not Stupid Certificate",
  },
  {
    quote: "My boss hasn't questioned a single decision since I put this on my desk.",
    name: "Sarah M.",
    tier: "Certified Genius",
  },
  {
    quote: "I bought the Galaxy Brain tier. I now speak at conferences. I have no idea why they keep inviting me back.",
    name: "James K.",
    tier: "Galaxy Brain Supreme",
  },
  {
    quote: "HR asked if this was real. I said yes. I got promoted.",
    name: "David K.",
    tier: "Certified Genius",
  },
  {
    quote: "My IQ didn't change but my confidence absolutely did. 12/10 would certify again.",
    name: "Tuan A.",
    tier: "Not Stupid Certificate",
  },
]

export default async function Home() {
  const language = await getLanguage()
  const tr = await getTranslations(language)

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-950 via-blue-900 to-indigo-950 text-white">
      <div className="sticky top-0 z-30 px-4 pt-4">
        <div className="mx-auto max-w-5xl flex justify-end">
          <div className="rounded-xl border border-blue-700/70 bg-blue-950/70 px-3 py-2 backdrop-blur-sm">
            <LanguagePicker currentLanguage={language} />
          </div>
        </div>
      </div>

      {/* Hero */}
      <section className="px-4 pt-16 pb-12 text-center">
        <div className="max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 bg-blue-800/50 border border-blue-700 rounded-full px-4 py-2 text-xs font-bold tracking-widest text-blue-300 uppercase mb-6">
            <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
            {tr.hero_badge}
          </div>

          <h1 className="text-5xl sm:text-7xl font-black mb-4 leading-tight tracking-tight">
            {tr.hero_title1}
            <br />
            <span className="text-yellow-400">{tr.hero_title2}</span>
          </h1>

          <p className="text-xl sm:text-2xl text-blue-200 mb-3 max-w-2xl mx-auto leading-relaxed">
            {tr.hero_subtitle}
          </p>

          <p className="text-base text-blue-300 mb-4 max-w-xl mx-auto">
            {tr.hero_description}
          </p>

          <div className="max-w-2xl mx-auto mb-8 rounded-2xl border border-yellow-400/30 bg-yellow-400/10 px-4 py-3 text-sm text-yellow-100">
            Novelty digital certificate for entertainment only. Not an academic, professional,
            legal, or official credential.
          </div>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-3 mb-6">
            <a
              href="#tiers"
              className="w-full sm:w-auto inline-block bg-yellow-400 text-black font-black py-4 px-10 rounded-full text-lg hover:bg-yellow-300 transition-colors shadow-lg shadow-yellow-400/30"
            >
              {tr.hero_cta}
            </a>
            <span className="text-blue-400 text-sm">{tr.hero_starting_at}</span>
          </div>

          {/* Social proof counter */}
          <div className="inline-flex items-center gap-2 bg-green-950/50 border border-green-700/40 rounded-full px-5 py-2.5 text-sm text-green-300 font-semibold">
            <span>🧠</span>
            <span>3,241 people officially certified so far</span>
            <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
          </div>
        </div>
      </section>

      {/* Sample certificate image */}
      <section className="px-4 pb-16">
        <p className="text-center text-blue-400 text-xs mb-6 font-semibold tracking-widest uppercase">
          {tr.example_label}
        </p>
        <div
          className="max-w-sm mx-auto shadow-2xl shadow-black/60"
          style={{ transform: 'rotate(-1.5deg)' }}
        >
          <Image
            src="/sample-certificate.png"
            alt="Sample Certified Not Stupid certificate"
            width={600}
            height={800}
            className="w-full h-auto rounded-sm"
            priority
          />
        </div>
        <p className="text-center text-blue-300 text-sm mt-6 max-w-sm mx-auto leading-relaxed">
          Your certificate will be uniquely generated by AI. No two are the same.
        </p>
      </section>

      {/* Tiers */}
      <section id="tiers" className="px-4 pb-20">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl sm:text-4xl font-black text-center mb-3">
            {tr.tiers_heading1} <span className="text-yellow-400">{tr.tiers_heading2}</span>
          </h2>
          <p className="text-center text-blue-300 mb-10 text-sm">{tr.tiers_subheading}</p>

          <div className="grid sm:grid-cols-3 gap-6 items-stretch">
            {TIERS.map((tier) => {
              const name = tr[`tier_${tier.id}_name` as keyof typeof tr] as string
              const tagline = tr[`tier_${tier.id}_tagline` as keyof typeof tr] as string
              const features = tierFeatures(tr, tier.id as 'basic' | 'premium' | 'supreme')

              return (
                <div
                  key={tier.id}
                  className={`bg-white rounded-2xl p-6 text-gray-800 flex flex-col relative ${tier.highlight ? 'ring-4 ring-yellow-400 sm:scale-105' : ''
                    }`}
                >
                  {tier.highlight && (
                    <div className="absolute -top-4 left-1/2 -translate-x-1/2 bg-yellow-400 text-black text-xs font-black px-4 py-1.5 rounded-full whitespace-nowrap">
                      {tr.tiers_most_popular}
                    </div>
                  )}

                  <div className="mb-4">
                    <span className="text-3xl">{tier.emoji}</span>
                    <h3 className="text-lg font-black mt-2 mb-1">{name}</h3>
                    <p className="text-gray-500 text-sm">{tagline}</p>
                  </div>

                  <div className="mb-5">
                    <span className="text-4xl font-black">{tier.price}</span>
                    <span className="text-gray-400 text-sm ml-1">{tr.tiers_one_time}</span>
                  </div>

                  <ul className="space-y-2 mb-8 flex-1">
                    {features.map((f, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-gray-600">
                        <span className="text-green-500 font-bold mt-0.5 shrink-0">✓</span>
                        {f}
                      </li>
                    ))}
                  </ul>

                  <a
                    href={LEMON_SQUEEZY_URLS[tier.id]}
                    className={`w-full block text-center py-4 rounded-xl font-black transition-colors text-base sm:text-sm ${tier.id === 'supreme'
                      ? 'bg-purple-600 text-white hover:bg-purple-700'
                      : tier.id === 'premium'
                        ? 'bg-amber-400 text-black hover:bg-amber-500'
                        : 'bg-gray-900 text-white hover:bg-gray-700'
                      }`}
                  >
                    {TIER_CTAS[tier.id]}
                  </a>
                </div>
              )
            })}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="px-4 pb-20">
        <div className="max-w-2xl mx-auto">
          <h2 className="text-2xl font-black text-center mb-8">{tr.faq_heading}</h2>

          <div className="mb-6 rounded-2xl border border-blue-700 bg-blue-900/40 px-4 py-4 text-sm text-blue-100">
            This product is a personalized digital novelty certificate delivered online after
            purchase. It is intended for humor and entertainment only.
          </div>

          <div className="space-y-6">
            {([1, 2, 3, 4] as const).map((n) => (
              <div key={n}>
                <h3 className="font-bold text-yellow-400 mb-1">
                  {tr[`faq_q${n}` as keyof typeof tr] as string}
                </h3>
                <p className="text-blue-200 text-sm leading-relaxed">
                  {tr[`faq_a${n}` as keyof typeof tr] as string}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="px-4 pb-20">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-2xl sm:text-3xl font-black text-center mb-2">What People Are Saying</h2>
          <p className="text-center text-blue-400 text-sm mb-10">Real quotes from real people*</p>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {TESTIMONIALS.map((t, i) => (
              <div
                key={i}
                className="bg-blue-900/40 border border-blue-700/50 rounded-2xl p-5 flex flex-col gap-3"
              >
                <div className="text-yellow-400 text-sm">⭐⭐⭐⭐⭐</div>
                <p className="text-blue-100 text-sm leading-relaxed flex-1">
                  &ldquo;{t.quote}&rdquo;
                </p>
                <div className="flex items-center justify-between mt-auto pt-3 border-t border-blue-700/40">
                  <span className="font-bold text-white text-sm">— {t.name}</span>
                  <span className="text-xs text-blue-400 bg-blue-800/50 px-2 py-1 rounded-full">{t.tier}</span>
                </div>
              </div>
            ))}
          </div>

          <p className="text-center text-blue-600 text-xs mt-6">
            *Verified by our verification department (us)
          </p>
        </div>
      </section>

      {/* Final CTA */}
      <section className="px-4 pb-20 text-center">
        <div className="max-w-md mx-auto">
          <h2 className="text-3xl font-black mb-3">{tr.fence_heading}</h2>
          <p className="text-blue-300 mb-6 text-sm">{tr.fence_sub}</p>
          <a
            href="#tiers"
            className="inline-block bg-yellow-400 text-black font-black py-4 px-10 rounded-full text-lg hover:bg-yellow-300 transition-colors"
          >
            {tr.fence_cta}
          </a>
        </div>
      </section>

      {/* Footer */}
      <footer className="text-sm text-center py-8 border-t border-white/10">
        <div className="mb-3 text-blue-300">
          Support:{' '}
          <a href="mailto:support@notstupidcert.com" className="underline hover:text-white">
            support@notstupidcert.com
          </a>
        </div>
        <div>
          <a href="/terms" className="mx-2 hover:text-blue-300">
            Terms
          </a>
          <a href="/privacy" className="mx-2 hover:text-blue-300">
            Privacy
          </a>
          <a href="/refunds" className="mx-2 hover:text-blue-300">
            Refunds
          </a>
        </div>
      </footer>
    </div>
  )
}
